apiVersion: v1
kind: Service
metadata:
  name: {{ include "rt-llm-proxy.fullname" . }}
  labels:
    {{- include "rt-llm-proxy.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "rt-llm-proxy.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
